### ISSUE TITLE
lib torch安装

### ISSUE THREAD

**Issue by lcaikk1314** [weixu000/libtorch-yolov3-deepsort#1]
请问：你的libtorch是如何安装的，我直接使用编译好的库，会报错“add_library cannot create target "caffe2_library" because another target with the same name already exists”

**Comment by weixu000** [comment]
hi，可以告诉我是怎么解决的么？有别人也在问

**Comment by weixu000** [comment]
https://github.com/pytorch/pytorch/issues/14352#issuecomment-441533855
