### ISSUE TITLE
Input image shape

### ISSUE THREAD

**Issue by chingswy** [weixu000/libtorch-yolov3-deepsort#11]
你好, 我想知道你代码里的YOLO输入图像的形状是什么? 我看另一个PyTorch版本的输入图像会resize到(416, 416), 但是你的代码中没有这样处理. 输入图像形状对结果有影响吗

**Comment by weixu000** [comment]
https://github.com/weixu000/libtorch-yolov3-deepsort/blob/a026aa378e01c4e66371e532b5ad69605517d939/processing/main.cpp#L30

可能会有影响，但是这里应该可以改
