### ISSUE TITLE
Does the Python model need to be transformed?

### ISSUE THREAD

**Issue by Earl-chen** [weixu000/libtorch-yolov3-deepsort#15]
Does the model obtained through Python need to be converted before it can be used? How to convert?
Thank you, brother!

**Comment by weixu000** [comment]
YOLO model weights can be directly downloaded from [its website](https://pjreddie.com/darknet/yolo/)
DeepSORT model weights from [](https://drive.google.com/drive/folders/1xhG0kRH1EX5B9_Iz8gQJb7UNnn_riXi6) needs transformation like #10
