### ISSUE TITLE
terminate called after throwing an instance of 'char const*'

### ISSUE THREAD

**Issue by mheriyanto** [weixu000/libtorch-yolov3-deepsort#18]
I got error when running:
`../build/bin$ ./processing ../../input/TownCentreXVID.avi`

![Selection_021](https://user-images.githubusercontent.com/22278148/80562498-23a0b300-8a12-11ea-836e-47c8d6c952c2.png)

**Comment by Nuller-CV** [comment]
Maybe your Detector construction don't have second parameter about "YoloType"

**Comment by Nuller-CV** [comment]
Maybe some file paths is wrong in Detector.cpp about YOLO model configure and weights
```case YOLOType::YOLOv3:
        net = std::make_unique<Darknet>("../models/yolov3.cfg");
        net->load_weights("../weights/yolov3.weights");
        break;
    case YOLOType::YOLOv3_TINY:
        net = std::make_unique<Darknet>("../models/yolov3-tiny.cfg");
        net->load_weights("../weights/yolov3-tiny.weights");
        break;
```

**Comment by zhuifengzhengren10840985** [comment]
Firstly, you have to download weights files, put them into a file named "weights".
Secondly, you have to change model configure and weights file paths in /detection/src/Detector.cpp 

61~66 lines:

        net = std::make_unique<Darknet>("../../models/yolov3.cfg");
        net->load_weights("../../weights/yolov3.weights");
        break;
    case YOLOType::YOLOv3_TINY:
        net = std::make_unique<Darknet>("../../models/yolov3-tiny.cfg");
        net->load_weights("../../weights/yolov3-tiny.weights");
        break;

**Comment by mheriyanto** [comment]
Okay, I solved this issue. Thanks @Nuller-CV and @zhuifengzhengren10840985
