### ISSUE TITLE
error: expected unqualified -id befor '[' token    auto[max_cls_score,max_cls]=pred.slice(1,5).max(1);

### ISSUE THREAD

**Issue by lcaikk1314** [weixu000/libtorch-yolov3-deepsort#2]
error: expected unqualified -id befor '[' token    auto[max_cls_score,max_cls]=pred.slice(1,5).max(1);

**Comment by weixu000** [comment]
抱歉用了很新的[语法糖](https://en.cppreference.com/w/cpp/language/structured_binding)，可能需要比较新的编译器才行，或者用std::get重写下。

**Comment by DancingJane** [comment]
我把gcc升级到7.4，错误还是在。这是为什么呢？我该怎么修改呢？谢谢啦

**Comment by deeplearning666** [comment]
可以参考这句话，在../libtorch-yolov3-deepsort-master/detection/src下Detector.cpp文件中，threshold_confidence中的auto[max_cls_score, max_cls] = pred.slice(1, 5).max(1);
改为
auto aa = pred.slice(1, 5).max(1);
torch::Tensor max_cls_score = std::get<0>(aa);
torch::Tensor max_cls = std::get<1>(aa);
