### ISSUE TITLE
cmake faied 

### ISSUE THREAD

**Issue by Vincent630** [weixu000/libtorch-yolov3-deepsort#3]
it seems you reference the lib of libtorch and that makes this error ,but i am not sure how to fix this issue ,can you give me some help about this and i wil appreciate it. 
CMake Error at /home/suning/libtorch/share/cmake/Caffe2/public/utils.cmake:16 (add_library):
  add_library cannot create target "torch_library" because another target
  with the same name already exists.  The existing target is an interface
  library created in source directory
  "/home/suning/libtorch-yolov3-deepsort-master/detection".  See
  documentation for policy CMP0002 for more details.

**Comment by LevineYang** [comment]
> it seems you reference the lib of libtorch and that makes this error ,but i am not sure how to fix this issue ,can you give me some help about this and i wil appreciate it.
> CMake Error at /home/suning/libtorch/share/cmake/Caffe2/public/utils.cmake:16 (add_library):
> add_library cannot create target "torch_library" because another target
> with the same name already exists. The existing target is an interface
> library created in source directory
> "/home/suning/libtorch-yolov3-deepsort-master/detection". See
> documentation for policy CMP0002 for more details.

Hi Vincent630, did you solve this error? I run into the same problem... please help, thank you

**Comment by intjun** [comment]
if (NOT TARGET ${DST})
    add_library(${DST} INTERFACE)
endif()

**Comment by CalvinPaean** [comment]
Go to the following directory in libtorch you installed, "libtorch/share/cmake/Caffe2/public".

Open "utils.cmake", on line #16, change that line to 

if (NOT TARGET ${DST})
add_library(${DST} INTERFACE)
endif()

**Comment by mheriyanto** [comment]
Thanks @CalvinPaean
