### ISSUE TITLE
No file detection_export.h found

### ISSUE THREAD

**Issue by wait1988** [weixu000/libtorch-yolov3-deepsort#4]

**Comment by weixu000** [comment]
https://github.com/weixu000/libtorch-yolov3-deepsort/blob/0a2d68d6608ce182fc6b24fe090cb8f41aa7a8a5/detection/CMakeLists.txt#L8

Does this result any error?

**Comment by wait1988** [comment]
Maybe the libtorch version I used is newer than yours.

**Comment by weixu000** [comment]
Sorry for late reply. I do not think it is due to libtorch. I think it is for CMake?
