### ISSUE TITLE
ckpt.bin

### ISSUE THREAD

**Issue by danieljpb** [weixu000/libtorch-yolov3-deepsort#5]
Is weights/ckpt.bin in Extractor.cpp same ckpt.t7 from https://drive.google.com/drive/folders/1xhG0kRH1EX5B9_Iz8gQJb7UNnn_riXi6 ?

When I rename to .bin and copy it in the weights directory I get a segmentation fault.

I am using Ubuntu 18.04 x86-64

Thanks so much

**Comment by weixu000** [comment]
Sorry I totally forgot this. I think the weights come from https://github.com/ZQPei/deep_sort_pytorch/blob/d7778f0e3a2cc2700f90f927184cc416da093fdf/deep_sort/deep/feature_extractor.py#L12

There the file seems to be a dict but mine is a series of binary. so you may need to change the file format.

Sorry again.
