### ISSUE TITLE
about the ckpt.bin 

### ISSUE THREAD

**Issue by Shengxiaolin** [weixu000/libtorch-yolov3-deepsort#6]
测试deep sort的时候，相关路径下没有ckpt.bin（忘记下载了），tracker也可以正常工作，请问这种情况是没有用到特征提取的网络吗？

**Comment by weixu000** [comment]
嗯？不太对啊。你确定用了DeepSORT那个类？里面总是会初始化Extractor啊

**Comment by Shengxiaolin** [comment]
感谢回复，确认过了类应该是对的，只是在load_form函数中ifstream fs(bin_path, ios_base::binary);这个bin_path如果不存在也不会报错，fs.read的时候同样也没有报错。

**Comment by weixu000** [comment]
没有检查IO错误，抱歉。这个ckpt.bin不是README中给出的那个。因为那个是python的dict，而我偷懒只能读取binary的tensor。如果要用需要在python里把每一层的那些parameters取出来二进制存储。

**Comment by Rainweic** [comment]
> 如果要用需要在python里把每一层的那些parameters取出来二进制存储。

请问下 这里的python的代码是指？？？
