### ISSUE TITLE
error: expected unqualified-id before ‘[’ token      auto[new_h, new_w] = letterbox_dim(img_dim, box_dim);

### ISSUE THREAD

**Issue by DancingJane** [weixu000/libtorch-yolov3-deepsort#7]
你好。我参考closed掉的这个issue，把gcc升级到7.4，但是错误还是存在。为什么呢？我该怎么修改呢？谢谢！

**Comment by weixu000** [comment]
如果这个版本支持c++17那应该是可以的，你可以关注一下编译的时候有没有`-std=c++17`这个开关。

但其实更简单的就是把`letterbox_dim`的返回值先保存下来，一个数组。分别赋给new_h和new_w就行。

这个东西只是语法糖，非常抱歉。
